### ISSUE TITLE
Image not centering correctly

### ISSUE THREAD

**Issue by BSmerT** [gumlet/php-image-resize#142] opened 2019-06-03 17:29 UTC
Hi,

I'm using this library to create the same image but in different sizes. Everything is ok when the height of the new size is greater than the width, the image is correctly centered vertically, but when the height is smaller than the width the image doesn't center horizontally.

This is my code:

```
if($size['height'] == 'auto'){
    $image->resizeToWidth($size['width'], true);
    $exactSize = false;
}elseif($size['width'] == 'auto'){
    $image->resizeToHeight($size['height'], true);
    $exactSize = false;
}else{
    $exactSize = [
        $size['width'],
        $size['height']
    ];

    $image->resizeToBestFit($size['width'], $size['height']);
}

if($image->save($target, null, null, null, $exactSize)){
    $response = $this->response->withType('application/json')
        ->withStringBody(true);
}
```

This code is inside a foreach, and $size is an array with height and width.

These are the results:

![issue](https://user-images.githubusercontent.com/19499355/58821271-b23e6180-8602-11e9-9d08-4e7c5d6bde06.png)

I don't understand why this happens, vertically is fine but not horizontally.

If you could help me I would be so grateful.

Thanks.

**Comment by peter279k** [comment] 2019-06-04 04:54
Hi @BSmerT, thank you for your report.

If possible, could you provide your image that you manipulate?

And it will help us to try reproducing issue easily :).

**Comment by BSmerT** [comment] 2019-06-04 15:11
Sure, here it is.

![A](https://user-images.githubusercontent.com/19499355/58884088-afe51180-86ad-11e9-9f40-77d60d92a2db.jpg)

Maybe the issue is here, I've recently uploaded a square image and it doesn't center at all.

ImageResize.php:293 
```
if( !empty($exact_size) && is_array($exact_size) ) {
    if ($this->getSourceHeight() < $this->getSourceWidth()) {
        $this->dest_x = 0;
        $this->dest_y = ($exact_size[1] - $this->getDestHeight()) / 2;
    }
    if ($this->getSourceHeight() > $this->getSourceWidth()) {
        $this->dest_x = ($exact_size[0] - $this->getDestWidth()) / 2;
        $this->dest_y = 0;
    }
}
```

I modified the code:
```
if( !empty($exact_size) && is_array($exact_size) ) {
    $this->dest_x = ($exact_size[0] - $this->getDestWidth()) / 2;
    $this->dest_y = ($exact_size[1] - $this->getDestHeight()) / 2;
    // if ($this->getSourceHeight() < $this->getSourceWidth()) {
    //     $this->dest_x = 0;
    //     $this->dest_y = ($exact_size[1] - $this->getDestHeight()) / 2;
    // }
    // if ($this->getSourceHeight() > $this->getSourceWidth()) {
    //     $this->dest_x = ($exact_size[0] - $this->getDestWidth()) / 2;
    //     $this->dest_y = 0;
    // }
}
```

This works perfectly. I don't know if this can affect something else, but with this modification all the images in every size, no matter what, are centered.

Thank for your quick response, btw!

**Comment by peter279k** [comment] 2019-06-05 06:02
@BSmerT, thank you for your reply.

It cannot reproduce issue because I got the result image looks fine for me without adding any comment in source code.

And I use the packcge version is `master` branch.

Here is my code snippets:

```php
<?php

require_once 'vendor/autoload.php';

use Gumlet\ImageResize;

// The file
$filename = 'issue_#142.jpg';

$image = new ImageResize($filename);

$image->resizeToBestFit(210, 300);
$image->save('image_issue#142_210_300.jpg', null, null, null, [210, 300]);

$filename = 'image_issue#142_210_300.jpg';

$image = new ImageResize($filename);

$image->resizeToBestFit(250, 120);
$image->save('image_issue#142_250_120.jpg', null, null, null, [250, 120]);
```
Resized image results are as follows:

210 * 300
![image](https://user-images.githubusercontent.com/9021747/58933551-34ad5980-879a-11e9-8b62-cc07e180e443.png)

250 * 120
![image](https://user-images.githubusercontent.com/9021747/58933568-468efc80-879a-11e9-9b7a-81b606492288.png)

**Comment by BSmerT** [comment] 2019-06-05 15:54
Hi @peter279k,

I noticed that in the second resize you used the resized version of the image, not the original. I've tried your solution and it did work, but if you use the original image in the second resize or if you resize it to 250x120 first, and then you resize it to 210x300 the results aren't correct.

Using your code snippet and resizing it to 250x120 first, these are the results:

250x120
![first_test](https://user-images.githubusercontent.com/19499355/58970732-fad35780-8787-11e9-994f-908c507d7508.png)

210x300
![second_test](https://user-images.githubusercontent.com/19499355/58970808-21918e00-8788-11e9-8abb-05576f7a6bcb.png)

**Comment by peter279k** [comment] 2019-06-06 03:04
Hi @BSmerT, thank you for your reply.

It's about the source width/height.

The image resizing work will check the source width/height before setting destination width/height.

Resizing to image size `210x300` is fine because the source height is longer than source width.

And resizing image size `250x120` is not good because source height is shorter than source width.

And the image source width and height checking will cause the image has the incorrect position.

As you mention your modified code, removing source width/height checking and set destination width/height will make the destination image position fine.

After tracing source code, it looks like this code is added since this [PR](https://github.com/gumlet/php-image-resize/pull/123/files) is merged.

Maybe @felipetnh can explain why it should check source width/height before setting destination width/height.

**Comment by peter279k** [comment] 2019-06-06 05:06
Please take a look at this, @adityapatadia, thanks.

**Comment by BSmerT** [comment] 2019-06-06 17:02
@felipetnh, @adityapatadia

I will try to find what's wrong and if I find something I'll tell you. Or if you find something please let me know.

Thanks @peter279k for your help.

**Comment by IsaacJara** [comment] 2019-06-19 18:54
Any update on this?

**Comment by peter279k** [comment] 2019-06-20 02:49
> 
> 
> Any update on this?

Hi @IsaacJara, thank you for your concern. Just wait for these authors I mention on previous comments 😄 .

**Comment by adityapatadia** [comment] 2019-06-25 07:38
> Please take a look at this, @adityapatadia, thanks.

I am not able to understand what action I need to take.

**Comment by peter279k** [comment] 2019-06-25 08:14
> > Please take a look at this, @adityapatadia, thanks.
> 
> I am not able to understand what action I need to take.

@adityapatadia, you can look at this [PR](https://github.com/gumlet/php-image-resize/pull/123/files) and know about this issue.

**Comment by adityapatadia** [comment] 2019-06-25 08:51
I have already checked it. It's merged. Is there any change required in current master branch behaviour? I am sorry I don't have time to look into this in great detail.

**Comment by peter279k** [comment] 2019-06-25 09:24
> I have already checked it. It's merged. Is there any change required in current master branch behaviour? I am sorry I don't have time to look into this in great detail.

@adityapatadia, I also mention some latest comments on this [PR](https://github.com/gumlet/php-image-resize/pull/123/files#r291005769).

**Comment by adityapatadia** [comment] 2020-07-04 21:16
In absence of @felipetnh I think we should get that fixed. @peter279k what do you say?

**Closed** 2023-10-11 14:09 UTC
